sudo: required

language: go

services:
  - docker

script: 
  - go get -t -v ./...
  - go test -v ./...
  - go build .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker build -t pastjean/scrumpolice .;
    docker tag pastjean/scrumpolice pastjean/scrumpolice:latest;
    docker push pastjean/scrumpolice:latest;
    fi