# Config for the scrumbot 
# the configuration file follows the [toml standard](https://github.com/toml-lang/toml)

# The shown username for the bot in the chat
bot_name = "Scrum Police"
bot_icon_url = "http://i.imgur.com/dzZvzXm.jpg"

# The slack "bot-user" token
slack_token = "xoxb-yourslacktokenhere"

[[team]]
name = "Most awesome team"
channel = "mostawesometeamchannel"
members = ["@pastjean", "@fboutin2", "@lbourdages"]

  [team.question_set]
  questions = [
      "What did you do yesterday? _(issue if needed)_",
      "What will you do today?",
      "Are you being blocked by someone for a review? who ? why ?"
  ]
  cron_schedule = "0 0 8 * * 1-5"
  grace_duration = "+55m"
  limit_time = "+65m"
  reminder = ":wave: Morning! Don't forget to fill in your scrum report!"

  [team.timesheet_reminder]
  message = ":wave: Evening! Don't forget to fill in your timesheet!"
  cron_schedule = "0 0 16 * * 1-5"